---
- name: Patch node | Prepare
{{- $assetsBaseUrl := .Values.assets.baseUrl | default ( printf "http://assets.%s.svc.%s" .Release.Namespace ( include "helm.clusterDomainName" $ ) ) }}
  set_fact:
    patch_base_url: {{ printf "%s/patches" $assetsBaseUrl | quote }}
    patch_files:
{{- range $path, $_ := $.Files.Glob "assets/patches/*.sh" }}
      - {{ base $path | quote }}
{{- end }}

- name: Patch node
  when:
    - kiss_os_exists
    - not kiss_os_dirty
  loop: {{ "{{ patch_files }}" | quote }}
  loop_control:
    loop_var: filename
  include_tasks: patches-entry.yaml
