apiVersion: v1
kind: Service
metadata:
  name: {{ include "omniverse-isaac-saas.name" . }}
  namespace: {{ .Values.portal.namespace }}
  labels:
    {{- include "omniverse-isaac-saas.labels" . | nindent 4 }}
  {{- with .Values.portal.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.portal.service.type }}
  {{- if .Values.portal.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.portal.service.loadBalancerIP }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "omniverse-isaac-saas.name" . }}
  ports:
    - name: http
      port: {{ .Values.portal.service.port }}
      targetPort: {{ .Values.portal.service.targetPort }}
      protocol: TCP
