apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.portal.serviceAccountName }}
  namespace: {{ .Values.portal.namespace }}
  labels:
    {{- include "omniverse-isaac-saas.labels" . | nindent 4 }}
