---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: dnsmasq
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
data:
  resolv.conf: |
    nameserver {{ .Values.cluster.nameservers.loadBalancer.ipv4 | default .Values.cluster.nameservers.incluster.ipv4 }}
    nameserver {{ .Values.network.nameservers.ns1 }}
    nameserver {{ .Values.network.nameservers.ns2 }}
    options timeout:2 attempts:3 rotate single-request-reopen
