---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "omniverse-nucleus.namespace" . | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    kubernetes.io/metadata.name: {{ include "omniverse-nucleus.namespace" . | quote }}
    app.kubernetes.io/part-of: "omniverse"
