{{- if .Values.nucleus.imagePullSecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "nucleus.imagePullSecret.name is required" .Values.nucleus.imagePullSecret.name | quote }}
  namespace: {{ include "omniverse-nucleus.namespace" . | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ dict "auths" (dict .Values.nucleus.imagePullSecret.registry (dict "username" .Values.nucleus.imagePullSecret.username "password" .Values.nucleus.imagePullSecret.password "auth" (printf "%s:%s" .Values.nucleus.imagePullSecret.username .Values.nucleus.imagePullSecret.password | b64enc))) | toJson | quote }}
{{- end }}
{{- if .Values.nucleus.secrets.passwords.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "nucleus.secrets.passwords.name is required" .Values.nucleus.secrets.passwords.name | quote }}
  namespace: {{ include "omniverse-nucleus.namespace" . | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
{{- .Values.nucleus.secrets.passwords.stringData | toYaml | nindent 2 }}
{{- end }}
{{- if .Values.nucleus.secrets.runtime.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "nucleus.secrets.runtime.name is required" .Values.nucleus.secrets.runtime.name | quote }}
  namespace: {{ include "omniverse-nucleus.namespace" . | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
{{- .Values.nucleus.secrets.runtime.stringData | toYaml | nindent 2 }}
{{- end }}
