---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "omniverse-nucleus.name" .) | quote }}
  namespace: {{ include "omniverse-nucleus.namespace" . | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
{{ include "omniverse-nucleus.labels" . | nindent 4 }}
    app.kubernetes.io/component: headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
{{ include "omniverse-nucleus.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      port: 8080
      targetPort: web
